name: disp_xr
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python > 3.13
  - pip>=21.3  # https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#editable-installation
  - git  # for pip install, due to setuptools_scm
  - click>=7.0
  - xarray
  - dask
  - rioxarray
  - types-PyYAML
  - rasterio
  - pyproj
  - gdal
  - numpy
  - scipy
  - pandas
  - netcdf4
  - h5netcdf
  - libgdal-hdf5
  - libgdal-netcdf
  - zarr
  - matplotlib
  - folium
  - mapclassify
# env
  - ruff
  - pre_commit
  - pydantic
  - mypy
# specific
  - asf_search
  - aiohttp
  - s3fs
  - pip:
      - opera_utils
      - dem_stitcher
      - tile_mate
